//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kursy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kursy()
        {
            this.Zadania = new HashSet<Zadania>();
        }
    
        public int IdKursu { get; set; }
        public int IdPrzedmiotu { get; set; }
        public int IdProwadzącego { get; set; }
        public int IdKlasy { get; set; }
        public string Tytuł { get; set; }
        public string Opis { get; set; }
    
        public virtual Klasy Klasy { get; set; }
        public virtual Nauczyciele Nauczyciele { get; set; }
        public virtual Przedmioty Przedmioty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadania> Zadania { get; set; }
    }
}
