//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozwiązania
    {
        public int IdRozwiązania { get; set; }
        public int IdUcznia { get; set; }
        public int IdZadania { get; set; }
        public byte[] TreśćRozwiązania { get; set; }
        public Nullable<byte> Ocena { get; set; }
        public string Komentarz { get; set; }
    
        public virtual Uczniowie Uczniowie { get; set; }
        public virtual Zadania Zadania { get; set; }
    }
}
