//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadania()
        {
            this.Rozwiązania = new HashSet<Rozwiązania>();
        }
    
        public int IdZadania { get; set; }
        public int IdKursu { get; set; }
        public string Treść { get; set; }
        public Nullable<System.DateTime> DataWstawienia { get; set; }
        public Nullable<System.DateTime> DataOddania { get; set; }
    
        public virtual Kursy Kursy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozwiązania> Rozwiązania { get; set; }
    }
}
