INSERT INTO Przedmioty (IdPrzedmiotu,NazwaPrzedmiotu) VALUES 
(1,'Jêzyk polski'),
(2,'Jêzyk angielski'),
(3,'Jêzyk niemiecki'),
(4,'Jêzyk rosyjski'),
(5,'Jêzyk francuski'),
(6,'Jêzyk hiszpañski'),
(7,'Jêzyk w³oski'),
(8,'Jêzyk duñski'),
(9,'Jêzyk ³aciñski'),
(10,'Matematyka'),
(11,'Informatyka'),
(12,'Technologia informacyjna'),
(13,'Technika'),
(14,'Przyroda'),
(15,'Biologia'),
(16,'Chemia'),
(17,'Fizyka'),
(18,'Geografia'),
(19,'Historia'),
(20,'Historia muzyki'),
(21,'Historia sztuki'),
(22,'Wiedza o spo³eczeñstwie'),
(23,'Wiedza o kulturze'),
(24,'Wiedza o tañcu'),
(25,'Podstawy przedsiêbiorczoœci'),
(26,'Edukacja dla bezpieczeñstwa'),
(27,'Wychowanie do ¿ycia w rodzinie'),
(28,'Filozofia')

